### ISSUE TITLE
Tracker: Basic Functionality

### ISSUE THREAD

**Issue by ksqsf** [OSH-2018/X-satu#1]
- [x] (Mar. 24) Network discovery: Find peers on a local network
- [x] (Mar. 24) Mount: FUSE
- [ ] (Mar. 31) Synchronization: Design a good protocol first!

This is a tracker for basic functionality. Each task is supposed to be finished by the corresponding date.

**Comment by ksqsf** [comment]
Second task marked solved. `python-fusepy` seems to do exactly the job. And it's fairly easy to use. Good for a quick demo. (Performance not evaluated yet.)

**Comment by ksqsf** [comment]
First task marked solved. `asyncio` is an elegant framework.
